config/routes.rb
Rails.application.routes.draw do
  #商品登録一覧ルート
  get 'items' => 'items#index'
  get 'items/new' => 'items#new'
  get 'items/confirm' => 'items#confirm'
  post 'items/confirm' => 'items#confirm'
  post 'items/back' => 'items#back'
  post 'items/create' => 'items#create'
  get 'items/complete' => 'items#complete'
  get 'items/show' => 'items#show'
  get 'items/:id'  => 'items#destroy'
  delete  'items/:id'  => 'items#destroy'
  patch 'carts/update' => 'carts#update'
  #ホーム画面ルート
  root 'stock_practice#home'
  get 'stock_practice/home'
  get 'contacts/new' => 'contacts#new'
  get 'about' => 'stock_practice#about'
  get 'help' => 'stock_practice#help'

  #ログイン関係ルート
  get 'sessions/new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'signup'  => 'users#new'

  #マイページ関係ルート
  get 'carts/index' => 'carts#index'
  get 'carts/confirm' => 'carts#confirm'
  post 'carts/confirm' => 'carts#confirm'
  #問い合わせ関係ルート


  resources :mypages
  resources :users
  resources :items, only: [:new, :create, :back, :edit, :update] do
    collection do
      post :confirm
    end
  end
  resources :items, only: [:index] do
    post 'add'=> 'favorites#create'
    delete '/add' => 'favorites#destroy'
    post 'in' => 'carts#create'
    delete '/in' => 'carts#destroy'
  end
  resources :logs, only: [:edit, :update, :create, :destroy]
  resources :contacts, only: [:new, :create]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :item
    validates_uniqueness_of :item_id, scope: :user_id

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_item
  def create
    @favorite = Favorite.create(user_id: current_user.id, item_id: @item.id)
  end

  def destroy
    @favorite = Favorite.find_by(user_id: current_user.id, item_id: @item.id)
    @favorite.destroy
  end

  private
  def set_item
    @item= Item.find(params[:item_id])
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorite.html.erb
<div class="button_to">
  <% if item.favorited_by?(current_user) %>
    <div class="favorite_star ">
      <%= button_to(item_add_path(item), method: :delete, remote: true, id: :"favorite_btn_#{item.id}") do %>
        <i class="fas fa-star fa-border star" ></i>
      <% end %>
    </div>
  <% else %>
    <div class="not_favorite_star">
      <%= button_to(item_add_path(item), method: :post, remote: true, id: :"favorite_btn_#{item.id}") do %>
        <i class="far fa-star fa-border"></i>
      <% end %>
    </div>
  <% end %>
</div>

app/views/favorites/create.js.erb
$('#favorite_btn_<%= @item.id %>').html("<%= j(render "favorites/favorite", item: @item) %>");

app/views/favorites/destroy.js.erb
$('#favorite_btn_<%= @item.id %>').html("<%= j(render "favorites/favorite", item: item) %>");