config/routes.rb
Rails.application.routes.draw do
  #商品登録一覧ルート
  get 'items' => 'items#index'
  get 'items/new' => 'items#new'
  get 'items/confirm' => 'items#confirm'
  post 'items/confirm' => 'items#confirm'
  post 'items/back' => 'items#back'
  post 'items/create' => 'items#create'
  get 'items/complete' => 'items#complete'
  get 'items/show' => 'items#show'
  get 'items/:id'  => 'items#destroy'
  delete  'items/:id'  => 'items#destroy'
  patch 'carts/update' => 'carts#update'
  #ホーム画面ルート
  root 'stock_practice#home'
  get 'stock_practice/home'
  get 'contacts/new' => 'contacts#new'
  get 'about' => 'stock_practice#about'
  get 'help' => 'stock_practice#help'

  #ログイン関係ルート
  get 'sessions/new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'signup'  => 'users#new'

  #マイページ関係ルート
  get 'carts/index' => 'carts#index'
  get 'carts/confirm' => 'carts#confirm'
  post 'carts/confirm' => 'carts#confirm'
  #問い合わせ関係ルート


  resources :mypages
  resources :users
  resources :items, only: [:new, :create, :back, :edit, :update] do
    collection do
      post :confirm
    end
  end
  resources :items, only: [:index] do
    post 'add'=> 'favorites#create'
    delete '/add' => 'favorites#destroy'
    post 'in' => 'carts#create'
    delete '/in' => 'carts#destroy'
  end
  resources :logs, only: [:edit, :update, :create, :destroy]
  resources :contacts, only: [:new, :create]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/cart.rb
class Cart < ApplicationRecord
    belongs_to :user
    belongs_to :item

    attribute :item_num, default: 1 #item_numのデフォルトの個数を１に設定している。カート内の編集にて個数の変更

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_item, only: [:create, :destroy,]

  def index
    carts = Cart.where(user_id: current_user.id).pluck(:item_id)  # ログイン中のユーザーのカートに入っているItem_idカラムを取得
    @cart = Item.find(carts)    # Itemsテーブルから、上で定義したカートに入っているレコードを取得
    cart = Cart.find_by(params[:id])
    @cart_id = cart.id
  end

  def update
    @cart = Cart.find(params[:id])
    @cart.save
      respond_to do |format|
      format.js
    end
  end

  def create
    @cart = Cart.create(user_id: current_user.id, item_id: @item.id)
  end

  def destroy
    @cart = Cart.find_by(user_id: current_user.id, item_id: @item.id)
    @cart.destroy
  end

  private
  def set_item
    @item= Item.find(params[:item_id])
  end

  def cart_params
  params.require(:item).permit([:cart_id, :item_num])
  end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<div class="cart_btn_to">
	<% if item.cart_in?(current_user) %>
		<div class="cart_out">
			<%= button_to(item_in_path(item), method: :delete, remote: true, id: :"cart_btn_#{item.id}") do %>
				<i class="fa-solid fa-check"></i>
			<% end %>
		</div>
	<% else %>
		<div class="cart_in">
			<%= button_to(item_in_path(item), method: :post, remote: true, id: :"favorite_btn_#{item.id}") do %>
				<i class="fa-solid fa-cart-plus"></i>
			<% end %>
		</div>
	<% end %>
</div>

app/views/carts/_form.html.erb
<span class="cart_count">
    <%= form_with(model:@cart, url: carts_update_path) do |form| %>
      <%= form.hidden_field :cart_id, value: @cart_id%>
      <%= form.select :item_num, [['1',1], ['2',2], ['3',3], ['4',4], ['5',5], ['6',6], ['7',7], ['8',8], ['9',9], ['10',10],], {}, {class: "ajax", :onchange => "changeTemplate($(this).val())"} %>
      <script>
        function changeTemplate(val){
          var item_num = val;
          console.log(item_num);
          $.ajax({
            url: "/carts/update",
            type: "post",
          })
        }
      </script>
      <%= form.submit %>
    <% end %>
</span>

app/views/carts/create.js.erb
$('#cart_btn_<%= @item.id %>').html("<%= j(render "carts/cart", item: @item) %>");

app/views/carts/destroy.js.erb
$('#cart_btn_<%= @item.id %>').html("<%= j(render "carts/cart", item: item) %>");

app/views/carts/index.erb
<h1>カート内商品一覧</h1>

<div class="top_index">
    <table class="table table-hover table-responsive align-middle">
        <thead>
            <tr>
                <div class="index_id">
                    <th>ID</th>
                </div>
                <div class="index_product_name">
                    <th>商品名</th>
                </div>
                <div class="index_arrival_source">
                    <th>入荷元</th>
                </div>
                <div class="index_manufactuer">
                    <th>製造元</th>
                </div>
                <div class="index_price">
                    <th>価格</th>
                </div>
                <div class="index_price">
                    <th>個数</th>
                </div>
            </tr>
        </thead>
        <tbody>
            <div class="buy_item_in_cart">
                <div class="">
                    <% @cart.each do |cart| %>
                        <tr>
                            <td><%= cart.id %></td>
                            <td><%= cart.product_name %></td>
                            <td><%= cart.arrival_source %></td>
                            <td><%= cart.manufactuer %></td>
                            <td><%= cart.price %></td>
                            <td class= "cart_update" id="cart_num_btn_<%= cart.id %> >
                                <%= render "form", {cart: cart} %>
                            </td>
                        <tr>
                    <% end %>
                </div>
            <div>
        </tbody>
    </table>
</div> 

app/views/carts/index.html.erb
<h1>カート内商品一覧</h1>

<div class="top_index">
	<table class="table table-hover table-responsive align-middle">
		<thead>
			<tr>
				<div class="index_id">
					<th>ID</th>
				</div>
				<div class="index_product_name">
					<th>商品名</th>
				</div>
				<div class="index_arrival_source">
					<th>入荷元</th>
				</div>
				<div class="index_manufactuer">
					<th>製造元</th>
				</div>
				<div class="index_price">
					<th>価格</th>
				</div>
				<div class="index_price">
					<th>個数</th>
				</div>
			</tr>
		</thead>
		<tbody>
			<div class="buy_item_in_cart">
				<div class="">
					<% @cart.each do |cart| %>
						<tr>
							<td><%= cart.id %></td>
							<td><%= cart.product_name %></td>
							<td><%= cart.arrival_source %></td>
							<td><%= cart.manufactuer %></td>
							<td><%= cart.price %></td>
							<td class= "cart_update" id= "<%= @cart_id %>" >
								<%= hidden_field_tag :cart_id, @cart_id %>
								<%= render "form", locals: {cart: cart} %>
							</td>
						<tr>
					<% end %>
				</div>
			<div>
		</tbody>
	</table>
</div>