config/routes.rb
Rails.application.routes.draw do
  #商品登録一覧ルート
  get 'items' => 'items#index'
  get 'items/new' => 'items#new'
  get 'items/confirm' => 'items#confirm'
  post 'items/confirm' => 'items#confirm'
  post 'items/back' => 'items#back'
  post 'items/create' => 'items#create'
  get 'items/complete' => 'items#complete'
  get 'items/show' => 'items#show'
  get 'items/:id'  => 'items#destroy'
  delete  'items/:id'  => 'items#destroy'
  patch 'carts/update' => 'carts#update'
  #ホーム画面ルート
  root 'stock_practice#home'
  get 'stock_practice/home'
  get 'contacts/new' => 'contacts#new'
  get 'about' => 'stock_practice#about'
  get 'help' => 'stock_practice#help'

  #ログイン関係ルート
  get 'sessions/new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'signup'  => 'users#new'

  #マイページ関係ルート
  get 'carts/index' => 'carts#index'
  get 'carts/confirm' => 'carts#confirm'
  post 'carts/confirm' => 'carts#confirm'
  #問い合わせ関係ルート


  resources :mypages
  resources :users
  resources :items, only: [:new, :create, :back, :edit, :update] do
    collection do
      post :confirm
    end
  end
  resources :items, only: [:index] do
    post 'add'=> 'favorites#create'
    delete '/add' => 'favorites#destroy'
    post 'in' => 'carts#create'
    delete '/in' => 'carts#destroy'
  end
  resources :logs, only: [:edit, :update, :create, :destroy]
  resources :contacts, only: [:new, :create]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/item.rb
class Item < ApplicationRecord
    has_many :logs, dependent: :destroy 
    accepts_nested_attributes_for :logs, allow_destroy: true

    has_many :favorites, dependent: :destroy
    has_many :users, through: :favorites
    
    has_many :carts, dependent: :destroy
    has_many :buy_items, dependent: :destroy

    with_options presence: true do
        validates :product_name, presence: true
        validates :arrival_source, presence: true
        validates :manufactuer, presence: true
    end

    def create
        @item = params[:item].permit(:product_name, :arrival_source, :manufactuer, :price)
        Item.create(@item)
    end

    def favorited_by?(user)
        favorites.where(user_id: user.id).exists?
    end

    def cart_in?(user)
        carts.where(user_id: user.id).exists?
    end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  include Pagy::Backend

  def index
    @pagy, @items = pagy(Item.all, items: 5)
  end

  def new
    @item = Item.new
    @log = @item.logs.new
  end

  def confirm
    @item = Item.new(item_params)
    #ここにLOGの定義が必要
  end

  def create
    #<!--入力画面-->
    @item = Item.new(item_params)
    if params[:back] || @item.save
      redirect_to action: :complete
    else
      flash.now[:danger] = "登録に失敗しました"
      render items_confirm_path
    end
  end

  def complete
  end

  def back
    @item = Item.new(item_params)
    render :new
  end

  def show
    favorites = Favorite.where(user_id: current_user.id).pluck(:item_id)  # ログイン中のユーザーのお気に入りのItem_idカラムを取得
    @favorite_list = Item.find(favorites)     # Itemsテーブルから、お気に入り登録済みのレコードを取得
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      flash[:success] = "編集完了しました"
      redirect_to action: :index
    else
      flash.now[:danger] = "編集に失敗しました"
      render 'edit'
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    flash[:success] = "削除しました"
    redirect_to action: :index
  end
  private

  def item_params
    params.require(:item).permit(:product_name, :arrival_source, :manufactuer, :price, logs_attributes: [:email, :tel, :_destroy, :id])
  end
  
end

app/helpers/items_helper.rb
module ItemsHelper
    include Pagy::Frontend
end

app/views/items/_update.html.erb
<%= form_with model: @item, data: { turbo: false }, local: true do |f| %> <!--import "@hotwired/turbo-rails"でのエラーをdata: { turbo: false }でこのHTML変換を無効化-->
  <div class='form-wrap'>
    <div class='form-header'>
      <h5 class='form-header-text'>
        編集画面
      </h5>
    </div>
  </div>

  <div class="correct-msg-box">
    <div class="contact-form">
      <div class="correct-text-field">
        <%= f.label :product_name, "商品名" %>
        <%= f.text_field :product_name, required: true %>
      </div>
      <div class="correct-text-field">
        <%= f.label :arrival_source, "入荷元" %>
        <%= f.text_field :arrival_source, required: true %>
      </div>
      <div class="correct-text-field">
        <%= f.label :manufactuer, "製造元" %>
        <%= f.text_field :manufactuer, required: true %>
      </div>
      <div class="correct-text-field">
        <%= f.label :price, "価格" %>
        <%= f.text_field :price, required: true %>
      </div>
        <div class="">
          <%= f.fields_for :logs do |log| %>
            <div class="">
              <%= log.label :tel, "電話番号" %>
              <%= log.text_field :tel, required: true%>
            </div>
            <div class="">
              <%= log.label :email, "email" %>
              <%= log.text_field :email, required: true %>
            </div>
          <% end %>
        </div>
    </div>
  </div>
  <div class="send-btn-contents">
    <%= f.submit "登録画面へ", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/items/complete.html.erb
<h1>登録完了</h1>

<div class="center jumbotron">
	<%= link_to "商品一覧", items_path, class: "btn btn-lg btn-primary" %>
	<%= link_to "商品新規追加", items_new_path, class: "btn btn-lg btn-primary" %>
</div>

app/views/items/confirm.html.erb
<h1>確認画面</h1>

<%= form_with model: @item, url: items_back_path, data: { turbo: false }, local: true do |f| %>
	<%= f.label :product_name, "商品名" %>
	<p><%= @item.product_name %></p>
	<%= f.hidden_field :product_name, required: true %>

	<%= f.label :arrival_source, "入荷元" %>
	<p><%= @item.arrival_source %></p>
	<%= f.hidden_field :arrival_source, required: true %>

	<%= f.label :manufactuer, "製造元" %>
	<p><%= @item.manufactuer %></p>
	<%= f.hidden_field :manufactuer, required: true %>

	<%= f.label :price, "価格" %>
	<p><%= @item.price %></p>
	<%= f.hidden_field :price, required: true %>

	<%= f.submit "入力画面に戻る", class: "btn btn-primary" %>
<% end %>

<%= form_with model: @item, url: items_create_path, data: { turbo: false }, local: true do |f| %>
	<%= f.hidden_field :product_name, required: true %>
	<%= f.hidden_field :arrival_source, required: true %>
	<%= f.hidden_field :manufactuer, required: true %>
	<%= f.hidden_field :price, required: true %>
	<%= f.fields_for :logs do |log| %>
	<% end %>
	<%= f.submit "登録する", class: "btn btn-primary" %>
<% end %>

app/views/items/create.html.erb
<h1>create</h1>
<p>Find me in app/views/top/show.html.erb</p>

app/views/items/destroy.html.erb
<div class="center jumbotron">
  <h1>Welcome</h1>
<!--商品一覧ページのリンク（itemのindex）-->
  <%= link_to "商品一覧", items_path, class: "btn btn-lg btn-primary" %>

<!--商品新規追加ページのリンク（itemのnew）-->
  <%= link_to "商品新規追加", items_new_path, class: "btn btn-lg btn-primary" %>
</div>

app/views/items/edit.html.erb
<%= render 'update' %>

app/views/items/index.html.erb
<h1>商品一覧</h1>

<div class="top_index">
    <table class="table table-hover table-responsive align-middle">
        <thead>
            <tr>
                <div class="index_id">
                    <th>ID</th>
                </div>
                <div class="index_product_name">
                    <th>商品名</th>
                </div>
                <div class="index_arrival_source">
                    <th>入荷元</th>
                </div>
                <div class="index_manufactuer">
                    <th>製造元</th>
                </div>
                <div class="index_price">
                    <th>価格</th>
                </div>
                <div class="index_created_at">
                    <th>作成日</th>
                </div>
            </tr>
        </thead>
        <tbody>
            <% @items.each do |item| %>
                <tr>
                    <td><%= item.id %></td>
                    <td><%= item.product_name %></td>
                    <td><%= item.arrival_source %></td>
                    <td><%= item.manufactuer %></td>
                    <td><%= item.price %></td>
                    <td><%= item.created_at %></td>
                    <td><%= link_to '編集', "items/#{item.id}/edit", class: "btn btn-lg btn-primary" %></td>
                    <td><%= link_to '削除', "items/#{item.id}", method: :delete, class: "btn btn-lg btn-primary" %></td>
                    <td class='cart-btn' id="cart_btn_<%= item.id %>">
                        <%= render partial: "carts/cart", locals: {item: item} %>
                        <script>
                            $(".cart-btn").click(function(){
                                location.reload();
                            })
                        </script>
                    </td>
                    <td class='star-btn' id="favorite_btn_<%= item.id %>">
                        <%= render partial: "favorites/favorite", locals: {item: item} %>
                        <script>
                            $(".star-btn").click(function(){
                                location.reload();
                            })
                        </script>
                    </td>
                <tr>
            <% end %>
        </tbody>
    </table>

    <div class="d-flex justify-content-center top_index_pagy">
    <%== pagy_bootstrap_nav(@pagy) %>
    </div>
</div>

app/views/items/new.html.erb
<h1>新規商品登録</h1>
<p>必要事項を記入してください</p>
<ul class="nav">
	<li class="current">1.入力</li>
	<li>2.確認</li>
	<li>3.完了</li>
</ul>

<!--入力画面-->

<%= form_with model: @item, url: items_confirm_path, data: { turbo: false }, local: true do |f| %> <!--import "@hotwired/turbo-rails"でのエラーをdata: { turbo: false }でこのHTML変換を無効化-->
  <div class='form-wrap'>
    <div class='form-header'>
      <h5 class='form-header-text'>
        新規登録
      </h5>
    </div>
  </div>

  <div class="correct-msg-box">
    <div class="contact-form">
      <div class="correct-text-field">
        <%= f.label :product_name, "商品名" %>
        <%= f.text_field :product_name, required: true %>
      </div>
      <div class="correct-text-field">
        <%= f.label :arrival_source, "入荷元" %>
        <%= f.text_field :arrival_source, required: true %>
      </div>
      <div class="correct-text-field">
        <%= f.label :manufactuer, "製造元" %>
        <%= f.text_field :manufactuer, required: true %>
      </div>
      <div class="correct-text-field">
        <%= f.label :price, "価格" %>
        <%= f.text_field :price, required: true %>
      </div>
        <div class="">
          <%= f.fields_for :logs do |log| %>
            <div class="">
              <%= log.label :tel, "電話番号" %>
              <%= log.text_field :tel, required: true%>
            </div>
            <div class="">
              <%= log.label :email, "email" %>
              <%= log.text_field :email, required: true %>
            </div>
          <% end %>
        </div>
    </div>
  </div>
  <div class="send-btn-contents">
    <%= f.submit "確認画面へ", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/items/show.html.erb
<h1>Favorite</h1>

<div class="top_index">
	<table class="table table-hover table-responsive align-middle">
		<thead>
				<tr>
						<div class="index_id">
								<th>ID</th>
						</div>
						<div class="index_product_name">
								<th>商品名</th>
						</div>
						<div class="index_arrival_source">
								<th>入荷元</th>
						</div>
						<div class="index_manufactuer">
								<th>製造元</th>
						</div>
						<div class="index_price">
								<th>価格</th>
						</div>
						<div class="index_created_at">
								<th>作成日</th>
				</tr>
		</thead>
		<tbody>
				<% if @favorite_list.present? %>
						<% @favorite_list.each do |item| %>
								<tr>
										<td><%= item.id %></td>
										<td><%= item.product_name %></td>
										<td><%= item.arrival_source %></td>
										<td><%= item.manufactuer%></td>
										<td><%= item.price %></td>
										<td><%= item.created_at%></td>
										<td class='star-btn' id="favorite_btn_<%= item.id %>">
											<%= render partial: "favorites/favorite", locals: {item: item} %>
										</td>
								</tr>
						<% end %>
				<% end %>
		</tbody>
	</table>
</div>