config/routes.rb
Rails.application.routes.draw do
  #商品登録一覧ルート
  get 'items' => 'items#index'
  get 'items/new' => 'items#new'
  get 'items/confirm' => 'items#confirm'
  post 'items/confirm' => 'items#confirm'
  post 'items/back' => 'items#back'
  post 'items/create' => 'items#create'
  get 'items/complete' => 'items#complete'
  get 'items/show' => 'items#show'
  get 'items/:id'  => 'items#destroy'
  delete  'items/:id'  => 'items#destroy'
  patch 'carts/update' => 'carts#update'
  #ホーム画面ルート
  root 'stock_practice#home'
  get 'stock_practice/home'
  get 'contacts/new' => 'contacts#new'
  get 'about' => 'stock_practice#about'
  get 'help' => 'stock_practice#help'

  #ログイン関係ルート
  get 'sessions/new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'signup'  => 'users#new'

  #マイページ関係ルート
  get 'carts/index' => 'carts#index'
  get 'carts/confirm' => 'carts#confirm'
  post 'carts/confirm' => 'carts#confirm'
  #問い合わせ関係ルート


  resources :mypages
  resources :users
  resources :items, only: [:new, :create, :back, :edit, :update] do
    collection do
      post :confirm
    end
  end
  resources :items, only: [:index] do
    post 'add'=> 'favorites#create'
    delete '/add' => 'favorites#destroy'
    post 'in' => 'carts#create'
    delete '/in' => 'carts#destroy'
  end
  resources :logs, only: [:edit, :update, :create, :destroy]
  resources :contacts, only: [:new, :create]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/buy_item.rb
class BuyItem < ApplicationRecord
    belongs_to :user
    belongs_to :item
end

app/models/cart.rb
class Cart < ApplicationRecord
    belongs_to :user
    belongs_to :item

    attribute :item_num, default: 1 #item_numのデフォルトの個数を１に設定している。カート内の編集にて個数の変更

end

app/models/contact.rb
class Contact < ApplicationRecord
    validates :name, presence: true
    validates :content, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :item
    validates_uniqueness_of :item_id, scope: :user_id

end

app/models/item.rb
class Item < ApplicationRecord
    has_many :logs, dependent: :destroy 
    accepts_nested_attributes_for :logs, allow_destroy: true

    has_many :favorites, dependent: :destroy
    has_many :users, through: :favorites
    
    has_many :carts, dependent: :destroy
    has_many :buy_items, dependent: :destroy

    with_options presence: true do
        validates :product_name, presence: true
        validates :arrival_source, presence: true
        validates :manufactuer, presence: true
    end

    def create
        @item = params[:item].permit(:product_name, :arrival_source, :manufactuer, :price)
        Item.create(@item)
    end

    def favorited_by?(user)
        favorites.where(user_id: user.id).exists?
    end

    def cart_in?(user)
        carts.where(user_id: user.id).exists?
    end

end

app/models/log.rb
class Log < ApplicationRecord
    belongs_to :item
    with_options presence: true do
        VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
        validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
    end
end

app/models/shipping.rb
class Shipping < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
    attr_accessor :remember_token
    has_secure_password
    has_many :logs
    has_many :favorites
    has_many :items, through: :favorites
    has_many :carts, dependent: :destroy
    has_many :buy_items, dependent: :destroy


    validates :login_id, presence: true, length: { maximum: 10 }
    validates :password, presence: true, length: { minimum: 6 }
    def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end

    def User.new_token
        SecureRandom.urlsafe_base64
    end

    def remember
        self.remember_token = User.new_token
        update_attribute(:remember_digest, User.digest(remember_token))
    end

    def authenticated?(remember_token)
        return false if remember_digest.nil?
        BCrypt::Password.new(remember_digest).is_password?(remember_token)
    end

    def forget
        update_attribute(:remember_digest, nil)
    end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_item, only: [:create, :destroy,]

  def index
    carts = Cart.where(user_id: current_user.id).pluck(:item_id)  # ログイン中のユーザーのカートに入っているItem_idカラムを取得
    @cart = Item.find(carts)    # Itemsテーブルから、上で定義したカートに入っているレコードを取得
    cart = Cart.find_by(params[:id])
    @cart_id = cart.id
  end

  def update
    @cart = Cart.find(params[:id])
    @cart.save
      respond_to do |format|
      format.js
    end
  end

  def create
    @cart = Cart.create(user_id: current_user.id, item_id: @item.id)
  end

  def destroy
    @cart = Cart.find_by(user_id: current_user.id, item_id: @item.id)
    @cart.destroy
  end

  private
  def set_item
    @item= Item.find(params[:item_id])
  end

  def cart_params
  params.require(:item).permit([:cart_id, :item_num])
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  include Pagy::Backend

  def index
    @pagy, @items = pagy(Item.all, items: 5)
  end

  def new
    @item = Item.new
    @log = @item.logs.new
  end

  def confirm
    @item = Item.new(item_params)
    #ここにLOGの定義が必要
  end

  def create
    #<!--入力画面-->
    @item = Item.new(item_params)
    if params[:back] || @item.save
      redirect_to action: :complete
    else
      flash.now[:danger] = "登録に失敗しました"
      render items_confirm_path
    end
  end

  def complete
  end

  def back
    @item = Item.new(item_params)
    render :new
  end

  def show
    favorites = Favorite.where(user_id: current_user.id).pluck(:item_id)  # ログイン中のユーザーのお気に入りのItem_idカラムを取得
    @favorite_list = Item.find(favorites)     # Itemsテーブルから、お気に入り登録済みのレコードを取得
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      flash[:success] = "編集完了しました"
      redirect_to action: :index
    else
      flash.now[:danger] = "編集に失敗しました"
      render 'edit'
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    flash[:success] = "削除しました"
    redirect_to action: :index
  end
  private

  def item_params
    params.require(:item).permit(:product_name, :arrival_source, :manufactuer, :price, logs_attributes: [:email, :tel, :_destroy, :id])
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @item = @user.items
    favorites = Favorite.where(user_id: current_user.id).pluck(:item_id)  # ログイン中のユーザーのお気に入りのItem_idカラムを取得
    @favorite_list = Item.find(favorites)     # Itemsテーブルから、お気に入り登録済みのレコードを取得
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Stock App!"
      redirect_to @user
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def back
  end

  def confirm
  end

  def complete
  end

  private

    def user_params
      params.require(:user).permit(:login_id,:password,:password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
    include Pagy::Frontend
end

app/helpers/mypage_helper.rb
module MypageHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
        session[:user_id] = user.id
    end

    def remember(user)
        user.remember
        cookies.permanent.signed[:user_id] = user.id
        cookies.permanent[:remember_token] = user.remember_token
    end

    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end

    def logged_in?
        !current_user.nil?
    end

    def forget(user)
        user.forget
        cookies.delete(:user_id)
        cookies.delete(:remember_token)
    end

    def log_out
        forget(current_user)
        session.delete(:user_id)
        @current_user = nil
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contacts_new_path %></li>
      <li><%= link_to "News", items_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "StockPractice", root_path, id: "logo" %>
    <!--ボタンダウンメニュー-->
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "Help",   help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "MyPage", mypages_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider">
                <li>
                  <%= button_to "Log out", logout_path, method: "delete" %>
                </li>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StockPractice</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
    <%= render 'layouts/shim' %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%
=begin%>
 <%= debug(params) if Rails.env.development? %> 
<%
=end%>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>